name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"  # modificado para rodar no minuto 0 de cada 12h
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pages: write
      id-token: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      # Cria o diretório dist se não existir
      - name: Create dist directory
        run: mkdir -p dist
        
      # Snake Animation
      - name: Generate snake animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: carolinechio
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}